In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [2]:
demand = pd.read_csv(r"C:\Users\ayton\Desktop\Groups_data\Group_8_Demand.csv")

In [3]:
demand.set_index(["Unnamed: 0"], inplace=True)

In [4]:
demand

LIPY  LIRQ  LICA  LIRA  LIPQ  LIMJ  LIPZ  LIPX  LIRN  LIBD
Unnamed: 0                                                            
LIPY           0   100    38    93    61    42    91    69    83    61
LIRQ          84     0    56   137   102    98   144   151   103    80
LICA          35    57     0    57    38    34    58    58    65    52
LIRA          88   142    65     0    97    95   120   119   152   102
LIPQ          68   100    40    83     0    72   113   101    81    59
LIMJ          49   101    42    79    65     0    87   106    72    59
LIPZ          85   141    56   127   132   115     0   172   110    75
LIPX          82   121    52   121   118   123   148     0   106    74
LIRN          82   127    71   169    85    78   116   108     0    99
LIBD          57    82    55   109    60    46    83    69    96     0

In [5]:
distan = pd.read_csv(r"C:\Users\ayton\Desktop\Groups_data\Group_8_Distances.csv")

In [6]:
distan.set_index(["Unnamed: 0"], inplace=True)

In [7]:
distan

LIRA        LIRQ        LICJ        LIPZ         LIMF  \
Unnamed: 0                                                                
LIRA          0.000000  250.643193  404.759550  412.001708   550.023153   
LIRQ        250.643193    0.000000  645.547025  209.225285   321.780985   
LICJ        404.759550  645.547025    0.000000  816.388380   901.883665   
LIPZ        412.001708  209.225285  816.388380    0.000000   369.379652   
LIMF        550.023153  321.780985  901.883665  369.379652     0.000000   
LIBD        353.920651  543.749521  453.613589  602.079002   865.484164   
LIPX        422.683166  178.199367  822.689364  114.724366   254.747674   
LIEO        276.986074  350.616247  433.213355  559.807987   499.619078   
LICA        445.880812  688.338876  284.923029  800.252092   995.903938   
LICC        526.125712  776.641265  190.037301  921.564342  1058.924225   
LIPE        322.013115   81.115581  722.376532  136.212707   296.629053   
LIMJ        415.386269  192.503832  774.872620  294.268005   134.708939   
LIRN        173.867218  412.369247  317.179906  537.042219   722.018414   
LIPY        215.153259  187.309894  605.302194  229.161277   498.529850   
LIPQ        452.636588  287.411020  850.186533   95.013438   460.327727   

                  LIBD        LIPX        LIEO        LICA         LICC  \
Unnamed: 0                                                                
LIRA        353.920651  422.683166  276.986074  445.880812   526.125712   
LIRQ        543.749521  178.199367  350.616247  688.338876   776.641265   
LICJ        453.613589  822.689364  433.213355  284.923029   190.037301   
LIPZ        602.079002  114.724366  559.807987  800.252092   921.564342   
LIMF        865.484164  254.747674  499.619078  995.903938  1058.924225   
LIBD          0.000000  670.489006  609.024598  251.783247   433.137931   
LIPX        670.489006    0.000000  510.598572  845.418184   947.536310   
LIEO        609.024598  510.598572    0.000000  616.838156   613.925708   
LICA        251.783247  845.418184  616.838156    0.000000   190.274072   
LICC        433.137931  947.536310  613.925708  190.274072     0.000000   
LIPE        584.230895  100.703504  428.063258  748.562166   847.196365   
LIMJ        734.108293  188.162430  391.566316  861.256968   927.407435   
LIRN        209.020578  572.362657  402.364706  275.989899   385.788112   
LIPY        383.196588  287.298800  446.436549  571.119473   696.187610   
LIPQ        584.009968  207.474536  633.355633  801.626999   938.295328   

                  LIPE        LIMJ        LIRN        LIPY        LIPQ  
Unnamed: 0                                                              
LIRA        322.013115  415.386269  173.867218  215.153259  452.636588  
LIRQ         81.115581  192.503832  412.369247  187.309894  287.411020  
LICJ        722.376532  774.872620  317.179906  605.302194  850.186533  
LIPZ        136.212707  294.268005  537.042219  229.161277   95.013438  
LIMF        296.629053  134.708939  722.018414  498.529850  460.327727  
LIBD        584.230895  734.108293  209.020578  383.196588  584.009968  
LIPX        100.703504  188.162430  572.362657  287.298800  207.474536  
LIEO        428.063258  391.566316  402.364706  446.436549  633.355633  
LICA        748.562166  861.256968  275.989899  571.119473  801.626999  
LICC        847.196365  927.407435  385.788112  696.187610  938.295328  
LIPE          0.000000  186.660820  474.155249  205.192751  223.888741  
LIMJ        186.660820    0.000000  587.321416  376.334373  389.276045  
LIRN        474.155249  587.321416    0.000000  310.442531  553.005551  
LIPY        205.192751  376.334373  310.442531    0.000000  245.315100  
LIPQ        223.888741  389.276045  553.005551  245.315100    0.000000

In [8]:
air_info = pd.read_csv(r"C:\Users\ayton\Desktop\Groups_data\Group_8_Airport_info.csv")

In [9]:
air_info

City Name ICAO Code  Latitude (deg)  Longitude (deg)  Runway (m)  \
0       Ciampino      LIRA       41.802425        12.602139        2208   
1        Firenze      LIRQ       43.808653        11.201225        1750   
2        Palermo      LICJ       38.182400        13.100582        3326   
3        Venezia      LIPZ       45.503200        12.351200        3300   
4         Torino      LIMF       45.200499         7.643164        3300   
5           Bari      LIBD       41.136600        16.756400        3000   
6         Verona      LIPX       45.395699        10.888500        3068   
7          Olbia      LIEO       40.916668         9.500000        2745   
8   LameziaTerme      LICA       38.906585        16.243402        2414   
9        Catania      LICC       37.467300        15.065800        2435   
10       Bologna      LIPE       44.535442        11.288667        2800   
11        Genova      LIMJ       44.414165         8.942184        3066   
12        Napoli      LIRN       40.884000        14.287800        2012   
13        Ancona      LIPY       43.616943        13.516667        2962   
14       Trieste      LIPQ       45.823000        13.485000        3000   

    Population     GDP  
0      6106485  200.84  
1      5827084  118.72  
2      1880634   89.36  
3      5658163  164.86  
4       477617  137.78  
5      2921914   77.47  
6      9002561   38.77  
7       640734   35.25  
8      1737196   33.61  
9      3126768   89.36  
10     7026812  163.75  
11     3422620   49.74  
12     6282927  109.63  
13     2281970   42.39  
14     3682052   46.55

Gravity Model:
    $D_{ij} = k\frac{(pop_{i}pop_{j})^{b1}(GDP_{i}GDP_{j})^{b2}}{(f\cdot d_{ij})^{b3}}$

Linear formula using logarithms: $\ln (D_{ij}) = \ln (k)+b1\cdot \ln (pop_ipop_j)+b2\cdot \ln(GDP_iGDP_j)-b3\cdot \ln(f\cdot d_{ij})$

In [10]:
col= []

In [11]:
for i in demand.index:
    for j in demand.index:
        if i!=j:
            col.append(i + "-" +j)

In [12]:
d_set = pd.DataFrame(index=col)

In [13]:
for i in demand.index:
    for j in demand.index:
        if i!=j:
            d_set.loc[i + "-" + j,"ln_Demand"]=math.log(demand.loc[i, j])
for i in demand.index:
    for j in demand.index:
        if i!=j:
            d_set.loc[i + "-" + j,"ln_pop"]=math.log(air_info[air_info["ICAO Code"]==i]["Population"].values*air_info[air_info["ICAO Code"]==j]["Population"].values)
for i in demand.index:
    for j in demand.index:
        if i!=j:
            d_set.loc[i + "-" + j,"ln_GDP"]=math.log(air_info[air_info["ICAO Code"]==i]["GDP"].values*air_info[air_info["ICAO Code"]==j]["GDP"].values)
f = 1.42/1.5
for i in demand.index:
    for j in demand.index:
        if i!=j:
            d_set.loc[i + "-" + j,"ln_fuel"]=-math.log(f*distan.loc[i, j])

In [14]:
d_set

ln_Demand     ln_pop    ln_GDP   ln_fuel
LIPY-LIRQ   4.605170  30.218577  8.523680 -5.177956
LIPY-LICA   3.637586  29.008333  7.261736 -6.292790
LIPY-LIRA   4.532599  30.265412  9.049421 -5.316542
LIPY-LIPQ   4.110874  29.759530  7.587439 -5.447735
LIPY-LIMJ   3.737670  29.686467  7.653722 -5.875670
...              ...        ...       ...       ...
LIBD-LIPQ   4.094345  30.006730  8.190418 -6.315110
LIBD-LIMJ   3.828641  29.933666  8.256700 -6.543848
LIBD-LIPZ   4.418841  30.436359  9.454987 -6.345580
LIBD-LIPX   4.234107  30.900769  8.007538 -6.453199
LIBD-LIRN   4.564348  30.541096  9.047002 -5.287624

[90 rows x 4 columns]

In [15]:
x = d_set.drop(["ln_Demand"], axis=1).values
y = d_set["ln_Demand"].values

In [16]:
print(x)

[[30.21857692  8.52368026 -5.1779562 ]
 [29.00833254  7.26173613 -6.29279019]
 [30.26541154  9.04942106 -5.31654237]
 [29.75953043  7.58743949 -5.44773527]
 [29.68646656  7.65372192 -5.8756698 ]
 [30.1891595   8.85200911 -5.37961778]
 [30.65356931  7.40455924 -5.60571455]
 [30.29389618  8.44402355 -5.68319056]
 [29.5282991   8.09680325 -5.8937399 ]
 [30.21857692  8.52368026 -5.1779562 ]
 [29.94581014  8.29159142 -6.47947303]
 [31.20288914 10.07927635 -5.46922215]
 [30.69700803  8.61729478 -5.60610508]
 [30.62394416  8.68357722 -5.20530782]
 [31.1266371   9.88186441 -5.28860336]
 [31.59104691  8.43441453 -5.12809473]
 [31.23137377  9.47387884 -5.96711094]
 [30.4657767   9.12665854 -6.24368047]
 [29.00833254  7.26173613 -6.29279019]
 [29.94581014  8.29159142 -6.47947303]
 [29.99264476  8.81733221 -6.04524344]
 [29.48676364  7.35535065 -6.63183517]
 [29.41369977  7.42163308 -6.70358468]
 [29.91639272  8.61992027 -6.63011856]
 [30.38080253  7.17247039 -6.68502316]
 [30.02112939  8.2119347 

In [17]:
print(y)

[4.60517019 3.63758616 4.53259949 4.11087386 3.73766962 4.51085951
 4.2341065  4.41884061 4.11087386 4.4308168  4.02535169 4.91998093
 4.62497281 4.58496748 4.9698133  5.01727984 4.63472899 4.38202663
 3.55534806 4.04305127 4.04305127 3.63758616 3.52636052 4.06044301
 4.06044301 4.17438727 3.95124372 4.47733681 4.95582706 4.17438727
 4.57471098 4.55387689 4.78749174 4.77912349 5.02388052 4.62497281
 4.21950771 4.60517019 3.68887945 4.41884061 4.27666612 4.72738782
 4.61512052 4.39444915 4.07753744 3.8918203  4.61512052 3.73766962
 4.36944785 4.17438727 4.46590812 4.66343909 4.27666612 4.07753744
 4.44265126 4.94875989 4.02535169 4.84418709 4.88280192 4.74493213
 5.14749448 4.70048037 4.31748811 4.40671925 4.79579055 3.95124372
 4.79579055 4.77068462 4.81218436 4.99721227 4.66343909 4.30406509
 4.40671925 4.84418709 4.26267988 5.12989871 4.44265126 4.35670883
 4.75359019 4.68213123 4.59511985 4.04305127 4.40671925 4.00733319
 4.69134788 4.09434456 3.8286414  4.41884061 4.2341065  4.5643

In [18]:
from sklearn.linear_model import LinearRegression
ml=LinearRegression()
ml.fit(x,y)

LinearRegression()

In [19]:
ml.intercept_

-5.8982755505716975

In [20]:
ml.coef_

array([0.35169365, 0.12825016, 0.26026062])

In [21]:
k = np.exp(-5.792748951225083)

In [23]:
air_info.set_index(["ICAO Code"], inplace=True)

In [24]:
air_info

City Name  Latitude (deg)  Longitude (deg)  Runway (m)  \
ICAO Code                                                              
LIRA           Ciampino       41.802425        12.602139        2208   
LIRQ            Firenze       43.808653        11.201225        1750   
LICJ            Palermo       38.182400        13.100582        3326   
LIPZ            Venezia       45.503200        12.351200        3300   
LIMF             Torino       45.200499         7.643164        3300   
LIBD               Bari       41.136600        16.756400        3000   
LIPX             Verona       45.395699        10.888500        3068   
LIEO              Olbia       40.916668         9.500000        2745   
LICA       LameziaTerme       38.906585        16.243402        2414   
LICC            Catania       37.467300        15.065800        2435   
LIPE            Bologna       44.535442        11.288667        2800   
LIMJ             Genova       44.414165         8.942184        3066   
LIRN             Napoli       40.884000        14.287800        2012   
LIPY             Ancona       43.616943        13.516667        2962   
LIPQ            Trieste       45.823000        13.485000        3000   

           Population     GDP  
ICAO Code                      
LIRA          6106485  200.84  
LIRQ          5827084  118.72  
LICJ          1880634   89.36  
LIPZ          5658163  164.86  
LIMF           477617  137.78  
LIBD          2921914   77.47  
LIPX          9002561   38.77  
LIEO           640734   35.25  
LICA          1737196   33.61  
LICC          3126768   89.36  
LIPE          7026812  163.75  
LIMJ          3422620   49.74  
LIRN          6282927  109.63  
LIPY          2281970   42.39  
LIPQ          3682052   46.55

In [25]:
for i in air_info.index:
    for j in (2020, 2030):
        air_info.loc[i,"Population"]=air_info.loc[i,"Population"]*1.96        
    air_info.loc[i,"2030pop"]=air_info.loc[i,"Population"]

In [27]:
demand_2030 = pd.DataFrame(index=air_info.index, columns=air_info.index)

In [28]:
demand_2030

ICAO Code LIRA LIRQ LICJ LIPZ LIMF LIBD LIPX LIEO LICA LICC LIPE LIMJ LIRN  \
ICAO Code                                                                    
LIRA       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIRQ       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LICJ       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIPZ       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIMF       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIBD       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIPX       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIEO       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LICA       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LICC       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIPE       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIMJ       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIRN       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIPY       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
LIPQ       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

ICAO Code LIPY LIPQ  
ICAO Code            
LIRA       NaN  NaN  
LIRQ       NaN  NaN  
LICJ       NaN  NaN  
LIPZ       NaN  NaN  
LIMF       NaN  NaN  
LIBD       NaN  NaN  
LIPX       NaN  NaN  
LIEO       NaN  NaN  
LICA       NaN  NaN  
LICC       NaN  NaN  
LIPE       NaN  NaN  
LIMJ       NaN  NaN  
LIRN       NaN  NaN  
LIPY       NaN  NaN  
LIPQ       NaN  NaN

Gravity Model:
    $D_{ij} = k\frac{(pop_{i}pop_{j})^{b1}(GDP_{i}GDP_{j})^{b2}}{(f\cdot d_{ij})^{b3}}$

In [29]:
math.pow(2,3)

8.0

In [30]:
k = 0.0030495874761702936
b1 = 0.35169365
b2 = 0.12825016
b3 = 0.26026062
f = 1.42/1.5

for i in demand_2030.index:
    for j in demand_2030.index:
        if i!=j:
            demand_2030.loc[i,j] = k*math.pow(air_info.loc[i,"2030pop"]*air_info.loc[j,"2030pop"],b1)*math.pow(air_info.loc[i,"GDP"]*air_info.loc[j,"GDP"],b2)/math.pow(f*distan.loc[i,j],b3)

In [31]:
demand_2030

ICAO Code        LIRA        LIRQ        LICJ        LIPZ        LIMF  \
ICAO Code                                                               
LIRA              NaN  402.234749  230.012667  364.836534  138.633793   
LIRQ       402.234749         NaN  187.306381  400.177564  146.563827   
LICJ       230.012667  187.306381         NaN  181.889769   72.607224   
LIPZ       364.836534  400.177564  181.889769         NaN  145.958067   
LIMF       138.633793  146.563827   72.607224  145.958067         NaN   
LIBD       273.068195  224.542212  152.484946  225.722299   84.136553   
LIPX       354.419852  408.044704  177.521926   472.36413  157.230657   
LIEO       154.295969  133.436392   81.810175  121.949968   51.459716   
LICA       192.412289   158.02129  128.782839  156.849223   60.700022   
LICC       256.898144  213.455083  199.465679   210.74728   83.269672   
LIPE       419.435224  552.159593  202.464467  498.047401  166.622026   
LIMJ       261.607601  293.862646  132.490348  271.626159  136.370035   
LIRN       449.662145  330.243599  229.056275  318.251855  120.710731   
LIPY       263.746491  251.428618  120.026757  246.272061    82.41248   
LIPQ       260.262223  269.345809  131.573304  370.865539    100.7612   

ICAO Code        LIBD        LIPX        LIEO        LICA        LICC  \
ICAO Code                                                               
LIRA       273.068195  354.419852  154.295969  192.412289  256.898144   
LIRQ       224.542212  408.044704  133.436392   158.02129  213.455083   
LICJ       152.484946  177.521926   81.810175  128.782839  199.465679   
LIPZ       225.722299   472.36413  121.949968  156.849223   210.74728   
LIMF        84.136553  157.230657   51.459716   60.700022   83.269672   
LIBD              NaN  214.646156   85.833071  152.469382  184.543469   
LIPX       214.646156         NaN  122.150242  151.213051  204.613055   
LIEO        85.833071  122.150242         NaN   64.015173    89.34107   
LICA       152.469382  151.213051   64.015173         NaN  171.058667   
LICC       184.543469  204.613055    89.34107  171.058667         NaN   
LIPE       245.294532  526.893225   141.00101  172.084487  232.265326   
LIMJ       154.042681   298.42115   96.174448  110.574577   151.19045   
LIRN       292.703678  306.114674  130.852276   203.74306  260.291346   
LIPY       154.989201  227.076526   78.961518  104.536045  138.393952   
LIPQ       166.327162  295.974369   86.332461  114.612759  153.346178   

ICAO Code        LIPE        LIMJ        LIRN        LIPY        LIPQ  
ICAO Code                                                              
LIRA       419.435224  261.607601  449.662145  263.746491  260.262223  
LIRQ       552.159593  293.862646  330.243599  251.428618  269.345809  
LICJ       202.464467  132.490348  229.056275  120.026757  131.573304  
LIPZ       498.047401  271.626159  318.251855  246.272061  370.865539  
LIMF       166.622026  136.370035  120.710731    82.41248    100.7612  
LIBD       245.294532  154.042681  292.703678  154.989201  166.327162  
LIPX       526.893225   298.42115  306.114674  227.076526  295.974369  
LIEO        141.00101   96.174448  130.852276   78.961518   86.332461  
LICA       172.084487  110.574577   203.74306  104.536045  114.612759  
LICC       232.265326   151.19045  260.291346  138.393952  153.346178  
LIPE              NaN  329.711844  354.454057  273.284067   319.92432  
LIMJ       329.711844         NaN  223.425152  155.533263    184.6251  
LIRN       354.454057  223.425152         NaN  224.065816  230.889816  
LIPY       273.284067  155.533263  224.065816         NaN  176.872563  
LIPQ        319.92432    184.6251  230.889816  176.872563         NaN

In [32]:
demand_2030.fillna(0, inplace=True)

In [33]:
demand_2030

ICAO Code        LIRA        LIRQ        LICJ        LIPZ        LIMF  \
ICAO Code                                                               
LIRA         0.000000  402.234749  230.012667  364.836534  138.633793   
LIRQ       402.234749    0.000000  187.306381  400.177564  146.563827   
LICJ       230.012667  187.306381    0.000000  181.889769   72.607224   
LIPZ       364.836534  400.177564  181.889769    0.000000  145.958067   
LIMF       138.633793  146.563827   72.607224  145.958067    0.000000   
LIBD       273.068195  224.542212  152.484946  225.722299   84.136553   
LIPX       354.419852  408.044704  177.521926  472.364130  157.230657   
LIEO       154.295969  133.436392   81.810175  121.949968   51.459716   
LICA       192.412289  158.021290  128.782839  156.849223   60.700022   
LICC       256.898144  213.455083  199.465679  210.747280   83.269672   
LIPE       419.435224  552.159593  202.464467  498.047401  166.622026   
LIMJ       261.607601  293.862646  132.490348  271.626159  136.370035   
LIRN       449.662145  330.243599  229.056275  318.251855  120.710731   
LIPY       263.746491  251.428618  120.026757  246.272061   82.412480   
LIPQ       260.262223  269.345809  131.573304  370.865539  100.761200   

ICAO Code        LIBD        LIPX        LIEO        LICA        LICC  \
ICAO Code                                                               
LIRA       273.068195  354.419852  154.295969  192.412289  256.898144   
LIRQ       224.542212  408.044704  133.436392  158.021290  213.455083   
LICJ       152.484946  177.521926   81.810175  128.782839  199.465679   
LIPZ       225.722299  472.364130  121.949968  156.849223  210.747280   
LIMF        84.136553  157.230657   51.459716   60.700022   83.269672   
LIBD         0.000000  214.646156   85.833071  152.469382  184.543469   
LIPX       214.646156    0.000000  122.150242  151.213051  204.613055   
LIEO        85.833071  122.150242    0.000000   64.015173   89.341070   
LICA       152.469382  151.213051   64.015173    0.000000  171.058667   
LICC       184.543469  204.613055   89.341070  171.058667    0.000000   
LIPE       245.294532  526.893225  141.001010  172.084487  232.265326   
LIMJ       154.042681  298.421150   96.174448  110.574577  151.190450   
LIRN       292.703678  306.114674  130.852276  203.743060  260.291346   
LIPY       154.989201  227.076526   78.961518  104.536045  138.393952   
LIPQ       166.327162  295.974369   86.332461  114.612759  153.346178   

ICAO Code        LIPE        LIMJ        LIRN        LIPY        LIPQ  
ICAO Code                                                              
LIRA       419.435224  261.607601  449.662145  263.746491  260.262223  
LIRQ       552.159593  293.862646  330.243599  251.428618  269.345809  
LICJ       202.464467  132.490348  229.056275  120.026757  131.573304  
LIPZ       498.047401  271.626159  318.251855  246.272061  370.865539  
LIMF       166.622026  136.370035  120.710731   82.412480  100.761200  
LIBD       245.294532  154.042681  292.703678  154.989201  166.327162  
LIPX       526.893225  298.421150  306.114674  227.076526  295.974369  
LIEO       141.001010   96.174448  130.852276   78.961518   86.332461  
LICA       172.084487  110.574577  203.743060  104.536045  114.612759  
LICC       232.265326  151.190450  260.291346  138.393952  153.346178  
LIPE         0.000000  329.711844  354.454057  273.284067  319.924320  
LIMJ       329.711844    0.000000  223.425152  155.533263  184.625100  
LIRN       354.454057  223.425152    0.000000  224.065816  230.889816  
LIPY       273.284067  155.533263  224.065816    0.000000  176.872563  
LIPQ       319.924320  184.625100  230.889816  176.872563    0.000000

In [34]:
demand_2030.to_csv('demand_2030.csv')